- hosts: jenkinsNodes
  become: true
  
  vars:
    jenkins_hostname: localhost
    jenkins_proxy_compatibility: true
    java_packages:
      - openjdk-11-jdk

  roles:
    - role: geerlingguy.java
    - role: ansible-role-jenkins
